version: "3.7"

services:

  api:
    build:
      context: .
      dockerfile: web.Dockerfile
    image: wolearn_api
    environment:
      ENVIRONMENT: dev
    ports:
      - 8080:80
  #   depends_on:
  #     - "db"

  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: test
  #     POSTGRES_PASSWORD: test
  #     POSTGRES_DB: test